### ISSUE TITLE
"not meant to use this directly"

### ISSUE THREAD

**Issue by Munter** [netlify/netlify-redirect-parser#11]
I have a feature suggestion in https://github.com/Munter/netlify-plugin-checklinks/issues/20 that I find is highly relevant, so I would like to use this library in a netlify build plugin.

The readme states I am `"not meant to use this directly"`, so I'm not quite sure it's a good idea.

Is the API stable enough that this is a good idea or should I find another solution?

**Comment by ehmicky** [comment]
Hi @Munter!

There is an ongoing work to add a redirects parsing utility directly available to Build plugins:

```js
module.exports = {
  onInit({ utils: { redirects } }) {
    redirects.add(...)
  }
}
```

This utility is most likely to use `netlify-redirect-parser` under the hood.

However there are quite many gotchas and things to take care off on the infrastructure side, so this PR is still currently in progress. If you subscribe to that PR, we'll update you as soon as we have this utility ready!

**Comment by ehmicky** [comment]
Redirects are now available using `netlifyConfig.redirects` :tada: 

```js
module.exports = {
  onPreBuild({ netlifyConfig: { redirects } }) {
    console.log(redirects)
  }
}
```

It is an array of objects with the same shape as `redirects` in `netlify.toml`, i.e. `{ from, to, status, force, conditions, query, headers, signed }`.
