### ISSUE TITLE
@netlify/config is outdated

### ISSUE THREAD

**Issue by eps1lon** [netlify/netlify-redirect-parser#21]
This project currently depends on `@netlify/config@0.x` while the latest version is 2.4.3 (https://www.npmjs.com/package/@netlify/config). This results in a lot of "duplicate" packages because it pulls in a lot of outdated and SemVer incompatible packages.

Is there currently a blocker that prevents using the latest version of `@netlify/config`?

**Comment by erezrokah** [comment]
Hi @eps1lon 👋  Thank you for opening the issue. This should be resolved by https://github.com/netlify/netlify-redirect-parser/issues/23

**Comment by eps1lon** [comment]
Thanks! Going to close this in anticipation of renovate bumping `@netlify/config`.
